# Generated by Django 4.2.1 on 2023-06-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_plant_growing_med'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='growing_med',
            new_name='growing_meds',
        ),
    ]
