# Generated by Django 4.2.1 on 2023-06-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_growing_med_plant_growing_meds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='growing_meds',
            new_name='growing_media',
        ),
    ]
